analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.7416756
  brandStrength: 0.8641245
  lightness: 0.5032223
  brandColors:
    - '#FFFFFF'
    - '#22AED1'
    - '#0F142A'
    - '#CC191F'
    - '#015B76'
  rhythmicContrast: 0.840494
typography_spectrum: 0.6087543948087841
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.3141783
favicon: null
name: markpowell
